version: 2
updates:
- package-ecosystem: docker
  directory: "/alfresco-helloworld-transformer-engine"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/helloworld-t-engine"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
